# shellcheck shell=bash
# The install stages, in the order entrypoint.sh runs them.

STATE_DIR=/run/installer
OUTPUT_DIR=/output
AIRGAP_K3S_DIR=/opt/airgap/k3s
AIRGAP_HARBOR_DIR=/opt/airgap/harbor
AIRGAP_DEMO_DIR=/opt/airgap/demo
AIRGAP_LONGHORN_DIR=/opt/airgap/longhorn
AIRGAP_KUBE_VIP_DIR=/opt/airgap/kube-vip
export ANSIBLE_CONFIG=/opt/ansible/ansible.cfg
export KUBECONFIG="${OUTPUT_DIR}/kubeconfig"

HARBOR_HOST=""
HARBOR_URL=""
HARBOR_ADMIN_PASSWORD=""
DEMO_IMAGE_REF=""
K3S_TOKEN=""
HARBOR_SC=""            # StorageClass Harbor actually landed on
CLUSTER_ENDPOINT=""     # what the emitted kubeconfig points at

# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
run_logged() {
  # Stream to the terminal and to the install log at the same time.
  set -o pipefail
  "$@" 2>&1 | sed 's/^/      /' | tee -a "${LOG_FILE}"
}

generate_password() {
  # Harbor demands >=8 chars with upper, lower and a digit.
  printf 'Hb%sA1' "$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-16)"
}

# --------------------------------------------------------------------------
# stage: inventory
# --------------------------------------------------------------------------
write_inventory() {
  mkdir -p "${STATE_DIR}" "${OUTPUT_DIR}/logs"
  chmod 700 "${STATE_DIR}"

  # With a VIP, every published service hangs off it instead of node 1, so the
  # registry keeps working when the machine that first served it is down.
  # HARBOR_URL, DEMO_IMAGE_REF, registries.yaml and the pull secret are all
  # derived from HARBOR_HOST, so this one line moves all of them.
  if [[ -n "${VIP_ADDRESS}" ]]; then
    HARBOR_HOST="${VIP_ADDRESS}"
    CLUSTER_ENDPOINT="${VIP_ADDRESS}"
  else
    HARBOR_HOST="${NODE_IPS[0]}"
    CLUSTER_ENDPOINT="${NODE_IPS[0]}"
  fi
  HARBOR_URL="http://${HARBOR_HOST}:${HARBOR_NODEPORT}"
  DEMO_IMAGE_REF="${HARBOR_HOST}:${HARBOR_NODEPORT}/${HARBOR_PROJECT}/${DEMO_IMAGE_NAME}:${DEMO_IMAGE_TAG}"

  # Passwords are passed through the environment, never written to disk.
  export INSTALLER_SSH_PASSWORD="${SSH_PASSWORD}"
  export INSTALLER_BECOME_PASSWORD="${BECOME_PASSWORD}"

  {
    echo "---"
    echo "# generated by the airgapped installer - all nodes are servers, so the"
    echo "# cluster runs embedded etcd and survives losing one machine."
    echo "k3s_cluster:"
    echo "  children:"
    echo "    server:"
    echo "      hosts:"
    local ip
    for ip in "${NODE_IPS[@]}"; do echo "        ${ip}:"; done
    echo "    agent:"
    echo "      hosts: {}"
    echo "  vars:"
    echo "    ansible_user: ${SSH_USER}"
    echo "    ansible_port: ${SSH_PORT}"
    echo "    ansible_password: \"{{ lookup('env', 'INSTALLER_SSH_PASSWORD') }}\""
    echo "    ansible_become: true"
    echo "    ansible_become_method: ansible.builtin.sudo"
    echo "    ansible_become_password: \"{{ lookup('env', 'INSTALLER_BECOME_PASSWORD') }}\""
    echo "    ansible_ssh_common_args: '-o PreferredAuthentications=password,keyboard-interactive,publickey'"
  } > "${STATE_DIR}/inventory.yml"
  chmod 600 "${STATE_DIR}/inventory.yml"

  resolve_cluster_token

  {
    echo "---"
    echo "k3s_version: \"${K3S_VERSION}\""
    echo "target_arch: \"${TARGET_ARCH}\""
    echo "token: \"${K3S_TOKEN}\""
    echo "api_endpoint: \"${NODE_IPS[0]}\""
    echo "cluster_context: \"${CLUSTER_NAME}\""
    echo "airgap_dir: \"${AIRGAP_K3S_DIR}\""
    echo "manage_firewall: true"
    echo "kubeconfig_endpoint: \"${CLUSTER_ENDPOINT}\""
    echo "vip_address: \"${VIP_ADDRESS}\""
    echo "server_config_yaml: |"
    echo "  write-kubeconfig-mode: \"0600\""
    echo "  secrets-encryption: true"
    if [[ -n "${VIP_ADDRESS}" ]]; then
      # The k3s_server role merges this over its own config with combine(), so a
      # tls-san list here REPLACES the one it derives from api_endpoint. Node 1
      # must therefore appear in our list too, or the API certificate silently
      # loses the name the other servers join through.
      echo "  tls-san:"
      echo "    - \"${NODE_IPS[0]}\""
      echo "    - \"${VIP_ADDRESS}\""
    fi
    echo "registries_config_yaml: |"
    echo "  mirrors:"
    echo "    \"${HARBOR_HOST}:${HARBOR_NODEPORT}\":"
    echo "      endpoint:"
    echo "        - \"${HARBOR_URL}\""
    if [[ -n "${VIP_ADDRESS}" ]]; then
      # The prereq role copies these onto every server before k3s first starts,
      # so k3s applies kube-vip as soon as its API is up. Rendered in
      # render_kube_vip(), which runs before the k3s install.
      echo "extra_manifests:"
      echo "  - \"${STATE_DIR}/manifests/kube-vip.yaml\""
    fi
    # Escape hatches for site-specific k3s flags, e.g. extra --tls-san entries.
    if [[ -n "${K3S_EXTRA_SERVER_ARGS:-}" ]]; then
      echo "extra_server_args: \"${K3S_EXTRA_SERVER_ARGS}\""
    fi
    if [[ -n "${K3S_EXTRA_AGENT_ARGS:-}" ]]; then
      echo "extra_agent_args: \"${K3S_EXTRA_AGENT_ARGS}\""
    fi
  } > "${STATE_DIR}/vars.yml"
  chmod 600 "${STATE_DIR}/vars.yml"

  ok "inventory written for ${#NODE_IPS[@]} node(s)"
  dim "k3s ${K3S_VERSION} · airgap bundle ${AIRGAP_K3S_DIR}"
}

# The cluster token encrypts k3s's bootstrap data, so it has to be the SAME on
# every run. Minting a fresh one against an existing cluster does not start a
# new cluster - it stops the old one dead with
#   "bootstrap data already found and encrypted with different token"
# on all three servers at once.
#
# So: reuse the token this output directory recorded; failing that, recover the
# real one from a running node; only mint a new token when there is genuinely no
# cluster to join.
resolve_cluster_token() {
  local token_file="${OUTPUT_DIR}/cluster-token"

  if [[ -s "${token_file}" ]]; then
    K3S_TOKEN="$(tr -d '\r\n' < "${token_file}")"
    dim "reusing the cluster token from ${token_file}"
    return 0
  fi

  # No record here, but the nodes may already be a cluster - ask them.
  # Pick the token out by shape rather than by line number: the raw module wraps
  # the output in a host header, an ssh known-hosts warning and a "Shared
  # connection closed" line, and which of those appear varies.
  local existing
  existing="$(ansible "${NODE_IPS[0]}" -i "${STATE_DIR}/inventory.yml" -m raw \
                -a 'cat /var/lib/rancher/k3s/server/token 2>/dev/null' 2>/dev/null \
              | grep -oE 'K10[A-Za-z0-9:._-]+' | head -n1 || true)"

  if [[ -n "${existing}" ]]; then
    K3S_TOKEN="${existing}"
    warn "recovered the existing cluster token from ${NODE_IPS[0]}"
    dim "a new token would have broken the running cluster"
  else
    K3S_TOKEN="$(openssl rand -hex 32)"
    dim "no existing cluster found - generating a new cluster token"
  fi

  umask 077
  printf '%s\n' "${K3S_TOKEN}" > "${token_file}"
  umask 022
}

# --------------------------------------------------------------------------
# stage: connectivity
# --------------------------------------------------------------------------
check_connectivity() {
  local attempt=0 max=3 out rc
  while true; do
    attempt=$((attempt + 1))
    set +e
    out="$(ansible k3s_cluster -m raw -a 'command -v python3 || echo NO_PYTHON3' 2>&1)"
    rc=$?
    set -e
    echo "${out}" >> "${LOG_FILE}"

    if (( rc == 0 )) && ! grep -q NO_PYTHON3 <<< "${out}"; then
      ok "all ${#NODE_IPS[@]} node(s) reachable over SSH with python3 present"
      return 0
    fi

    if grep -q NO_PYTHON3 <<< "${out}"; then
      die "a node has no python3, which Ansible needs. Install python3 on every node
      (apt-get install python3) and run the installer again."
    fi

    if grep -qiE 'permission denied|invalid/incorrect password|authentication failure' <<< "${out}"; then
      warn "authentication failed"
      if (( attempt >= max )) || [[ -n "${K3S_NODE_IPS:-}" ]] || ! have_tty; then
        die "could not authenticate to the nodes as '${SSH_USER}' after ${attempt} attempt(s)."
      fi
      ask_secret SSH_PASSWORD "Password for ${SSH_USER}@<node>"
      [[ "${SSH_USER}" == "root" ]] && BECOME_PASSWORD="${SSH_PASSWORD}"
      export INSTALLER_SSH_PASSWORD="${SSH_PASSWORD}"
      export INSTALLER_BECOME_PASSWORD="${BECOME_PASSWORD}"
      continue
    fi

    printf '%s\n' "${out}" | sed 's/^/      /' >&2
    die "could not reach every node over SSH on port ${SSH_PORT}. See the output above."
  done
}

# --------------------------------------------------------------------------
# stage: playbooks
# --------------------------------------------------------------------------
run_preflight() {
  run_logged ansible-playbook /opt/ansible/playbooks/00-preflight.yml \
    -e "@${STATE_DIR}/vars.yml" \
    || die "preflight failed - fix the issues reported above and re-run"
  ok "all nodes pass preflight"
}

run_offline_packages() {
  run_logged ansible-playbook /opt/ansible/playbooks/10-offline-packages.yml \
    || die "could not satisfy OS package prerequisites offline"
  ok "OS prerequisites satisfied from the offline bundle"
}

run_k3s_install() {
  info "copying $(du -sh "${AIRGAP_K3S_DIR}" | cut -f1) of artifacts to each node - this is the slow part"

  # On a re-run against a live cluster, restarting all three servers at once can
  # cost etcd its quorum. One host at a time is slower but safe; a first install
  # has no cluster to lose, so it keeps the default parallelism.
  local forks=(--forks 5)
  if kubectl get nodes >/dev/null 2>&1; then
    forks=(--forks 1)
    dim "existing cluster detected - applying one node at a time to protect etcd quorum"
  fi

  run_logged ansible-playbook "${forks[@]}" /opt/k3s-ansible/playbooks/site.yml \
    -e "@${STATE_DIR}/vars.yml" \
    || die "k3s installation failed"
  ok "k3s ${K3S_VERSION} installed on ${#NODE_IPS[@]} node(s)"
}

fetch_cluster_access() {
  run_logged ansible-playbook /opt/ansible/playbooks/30-post-install.yml \
    -e "@${STATE_DIR}/vars.yml" \
    || die "could not retrieve the kubeconfig"

  local deadline=$((SECONDS + 300)) ready=0 total="${#NODE_IPS[@]}"
  while (( SECONDS < deadline )); do
    ready="$(kubectl get nodes --no-headers 2>/dev/null \
             | awk '$2 == "Ready" { n++ } END { print n + 0 }')"
    (( ready >= total )) && break
    sleep 5
  done
  (( ready >= total )) || die "only ${ready}/${total} nodes reached Ready. Check 'kubectl get nodes' with ${KUBECONFIG}."
  ok "${ready}/${total} nodes Ready"
  kubectl get nodes -o wide 2>&1 | sed 's/^/      /' | tee -a "${LOG_FILE}"
}

# --------------------------------------------------------------------------
# stage: kube-vip
# --------------------------------------------------------------------------
render_kube_vip() {
  local tmpl="${AIRGAP_KUBE_VIP_DIR}/kube-vip.yaml.tmpl"
  [[ -f "${tmpl}" ]] || die "kube-vip manifest template missing: ${tmpl}"

  # The interface name goes into a DaemonSet, so it has to be valid on every
  # server. Preflight records the common one; an explicit setting overrides it.
  local iface="${VIP_INTERFACE}"
  if [[ -z "${iface}" && -r "${STATE_DIR}/vip-interface" ]]; then
    iface="$(tr -d '[:space:]' < "${STATE_DIR}/vip-interface")"
  fi
  [[ -n "${iface}" ]] || die "could not determine the network interface for the VIP.
     Set K3S_VIP_INTERFACE (e.g. ens18) and run again."

  mkdir -p "${STATE_DIR}/manifests"
  sed -e "s|@@VIP_ADDRESS@@|${VIP_ADDRESS}|g" \
      -e "s|@@VIP_INTERFACE@@|${iface}|g" \
      "${tmpl}" > "${STATE_DIR}/manifests/kube-vip.yaml"

  if grep -q '@@' "${STATE_DIR}/manifests/kube-vip.yaml"; then
    die "unsubstituted placeholder left in the kube-vip manifest"
  fi
  # There is no cluster to validate against yet - even --dry-run=client needs one
  # to resolve resource kinds - so check the manifest offline instead: it must
  # parse as YAML and contain the four objects kube-vip needs to run.
  python3 - "${STATE_DIR}/manifests/kube-vip.yaml" <<'PY' \
    || die "the rendered kube-vip manifest is not usable - see the error above"
import sys, yaml
docs = [d for d in yaml.safe_load_all(open(sys.argv[1])) if d]
kinds = sorted(d.get("kind", "?") for d in docs)
want = ["ClusterRole", "ClusterRoleBinding", "DaemonSet", "ServiceAccount"]
missing = [k for k in want if k not in kinds]
if missing:
    sys.exit(f"kube-vip manifest is missing {', '.join(missing)} (found: {', '.join(kinds)})")
ds = next(d for d in docs if d.get("kind") == "DaemonSet")
env = {e["name"]: e.get("value") for e in
       ds["spec"]["template"]["spec"]["containers"][0].get("env", [])}
for key in ("address", "vip_interface"):
    if not env.get(key):
        sys.exit(f"kube-vip DaemonSet has no {key} set")
print(f"  {len(docs)} objects, address={env['address']} interface={env['vip_interface']}")
PY

  ok "kube-vip ${KUBE_VIP_VERSION} manifest rendered for ${VIP_ADDRESS} on ${iface}"
  dim "k3s applies it from its manifests directory as soon as the API is up"
}

verify_vip() {
  info "waiting for the API to answer on ${VIP_ADDRESS}"
  local deadline=$((SECONDS + 240)) code=
  while (( SECONDS < deadline )); do
    # Any HTTP answer proves the API is reachable through the VIP. k3s requires
    # authentication for /readyz, so it replies 401 rather than "ok" - checking
    # for the body text reports a perfectly working VIP as broken.
    code="$(curl -sk --max-time 5 -o /dev/null -w '%{http_code}' \
            "https://${VIP_ADDRESS}:6443/version" 2>/dev/null || true)"
    if [[ "${code}" =~ ^(200|401|403)$ ]]; then
      ok "API server reachable on the VIP"
      run_logged kubectl -n kube-system rollout status daemonset/kube-vip-ds --timeout=120s \
        || warn "kube-vip is serving the VIP but its DaemonSet is not fully rolled out"
      return 0
    fi
    sleep 5
  done

  # The cluster itself is fine - only the VIP is not up. Degrade loudly rather
  # than throwing away a working install.
  warn "the VIP ${VIP_ADDRESS} never answered on :6443."
  warn "The cluster is up; kubectl still works against ${NODE_IPS[0]}."
  warn "Check: kubectl -n kube-system get pods -l app.kubernetes.io/name=kube-vip-ds"
  return 0
}

# --------------------------------------------------------------------------
# stage: Longhorn
# --------------------------------------------------------------------------
prepare_longhorn_nodes() {
  run_logged ansible-playbook /opt/ansible/playbooks/20-longhorn-node-prep.yml \
    -e "@${STATE_DIR}/vars.yml" \
    -e "longhorn_data_path=${LONGHORN_DATA_PATH}" \
    -e "longhorn_fs_label=${LONGHORN_FS_LABEL}" \
    -e "longhorn_data_device=${LONGHORN_DATA_DEVICE:-}" \
    || die "could not prepare the nodes' data disks for Longhorn"
  ok "data disks formatted and mounted at ${LONGHORN_DATA_PATH}"
}

install_longhorn() {
  local chart
  chart="$(find "${AIRGAP_LONGHORN_DIR}" -name 'longhorn-*.tgz' -print -quit)"
  [[ -n "${chart}" ]] || die "no Longhorn chart found in ${AIRGAP_LONGHORN_DIR}"

  local ui_args=()
  if [[ -n "${LONGHORN_UI_NODEPORT}" ]]; then
    ui_args=(--set "service.ui.type=NodePort" --set "service.ui.nodePort=${LONGHORN_UI_NODEPORT}")
  fi

  info "installing $(basename "${chart}") - images come from the local containerd store"
  run_logged helm upgrade --install longhorn "${chart}" \
    --namespace "${LONGHORN_NAMESPACE}" --create-namespace \
    --values /opt/longhorn/values-base.yaml \
    --set "defaultSettings.defaultDataPath=${LONGHORN_DATA_PATH}" \
    --set "defaultSettings.defaultReplicaCount=${LONGHORN_REPLICA_COUNT}" \
    --set "persistence.defaultClassReplicaCount=${LONGHORN_REPLICA_COUNT}" \
    --set "persistence.defaultClass=${LONGHORN_DEFAULT_STORAGE_CLASS}" \
    "${ui_args[@]}" \
    --wait --timeout 20m \
    || die "Longhorn did not become ready. Inspect: kubectl -n ${LONGHORN_NAMESPACE} get pods"

  # helm --wait only proves the pods are up. Longhorn is not actually usable
  # until its own node objects report the disks as schedulable.
  info "waiting for Longhorn to accept every node's disk"
  local deadline=$((SECONDS + 600)) ready=0 total="${#NODE_IPS[@]}"
  while (( SECONDS < deadline )); do
    ready="$(kubectl -n "${LONGHORN_NAMESPACE}" get nodes.longhorn.io \
              -o jsonpath='{range .items[*]}{.status.conditions[?(@.type=="Schedulable")].status}{"\n"}{end}' \
              2>/dev/null | grep -c '^True$' || true)"
    (( ready >= total )) && break
    sleep 10
  done
  (( ready >= total )) || die "only ${ready}/${total} nodes offered storage to Longhorn.
      Check: kubectl -n ${LONGHORN_NAMESPACE} get nodes.longhorn.io -o wide"
  ok "${ready}/${total} nodes contributing storage"

  if [[ "${LONGHORN_DEFAULT_STORAGE_CLASS}" == "true" ]]; then
    set_longhorn_default
  fi

  kubectl get storageclass 2>&1 | sed 's/^/      /' | tee -a "${LOG_FILE}"

  if [[ -n "${LONGHORN_UI_NODEPORT}" ]]; then
    ok "Longhorn UI on http://${NODE_IPS[0]}:${LONGHORN_UI_NODEPORT} (no authentication)"
  else
    dim "UI: kubectl -n ${LONGHORN_NAMESPACE} port-forward svc/longhorn-frontend 8080:80"
  fi
}

# --------------------------------------------------------------------------
# stage: Harbor
# --------------------------------------------------------------------------
# Two StorageClasses both claiming to be default is a real failure mode: which
# one a PVC gets is then arbitrary. Demote k3s's local-path and prove exactly
# one default remains. local-path stays usable by name.
set_longhorn_default() {
  # k3s re-applies its bundled manifests every time a server starts, which puts
  # the default-class annotation straight back on local-path. Annotating alone
  # therefore lasts only until the next reboot, and the cluster is then left
  # with *two* classes claiming to be default - so a PVC that names none gets an
  # arbitrary one.
  #
  # A .skip file tells k3s to stop re-applying that one manifest. The
  # StorageClass and its provisioner are left exactly as they are, so local-path
  # keeps working by name; k3s simply stops overwriting our change. The cost is
  # that a k3s upgrade will no longer refresh the local-path provisioner - delete
  # the .skip file if you want that back.
  run_logged ansible k3s_cluster -i "${STATE_DIR}/inventory.yml" \
    -m ansible.builtin.file \
    -a "path=/var/lib/rancher/k3s/server/manifests/local-storage.yaml.skip state=touch mode=0644" \
    || warn "could not pin the local-storage addon - local-path may reclaim the default class on reboot"

  if kubectl get storageclass local-path >/dev/null 2>&1; then
    run_logged kubectl annotate storageclass local-path \
      storageclass.kubernetes.io/is-default-class=false --overwrite \
      || warn "could not demote the local-path StorageClass"
  fi

  local defaults
  defaults="$(kubectl get storageclass -o json 2>/dev/null \
    | jq -r '.items[]
             | select(.metadata.annotations["storageclass.kubernetes.io/is-default-class"] == "true")
             | .metadata.name' | sort | tr '\n' ' ' | sed 's/ $//')"

  if [[ "${defaults}" != "longhorn" ]]; then
    die "expected 'longhorn' to be the only default StorageClass, got: ${defaults:-none}.
      Check: kubectl get storageclass"
  fi
  ok "longhorn is the default StorageClass (local-path kept, not default)"
}

# Which StorageClass Harbor's volumes land on. A PVC's class is immutable once
# bound, so an existing Harbor keeps whatever it already has - otherwise the
# helm upgrade would just fail with a confusing error.
harbor_storage_class() {
  if [[ -n "${HARBOR_STORAGE_CLASS}" ]]; then
    printf '%s' "${HARBOR_STORAGE_CLASS}"; return 0
  fi
  local existing
  existing="$(kubectl -n "${HARBOR_NAMESPACE}" get pvc harbor-registry \
                -o jsonpath='{.spec.storageClassName}' 2>/dev/null || true)"
  if [[ -n "${existing}" ]]; then
    printf '%s' "${existing}"; return 0
  fi
  if kubectl get storageclass longhorn >/dev/null 2>&1; then
    printf 'longhorn'; return 0
  fi
  printf 'local-path'
}

install_harbor() {
  local chart
  chart="$(find "${AIRGAP_HARBOR_DIR}" -name 'harbor-*.tgz' -print -quit)"
  [[ -n "${chart}" ]] || die "no Harbor chart found in ${AIRGAP_HARBOR_DIR}"

  # Reuse the password on re-runs so pull secrets stay valid.
  if kubectl -n "${HARBOR_NAMESPACE}" get secret harbor-core >/dev/null 2>&1; then
    HARBOR_ADMIN_PASSWORD="$(kubectl -n "${HARBOR_NAMESPACE}" get secret harbor-core \
      -o jsonpath='{.data.HARBOR_ADMIN_PASSWORD}' | base64 -d)"
    dim "reusing the existing Harbor admin password"
  else
    HARBOR_ADMIN_PASSWORD="$(generate_password)"
  fi

  HARBOR_SC="$(harbor_storage_class)"
  info "installing $(basename "${chart}") on the '${HARBOR_SC}' StorageClass"
  dim "images come from the local containerd store"
  run_logged helm upgrade --install harbor "${chart}" \
    --namespace "${HARBOR_NAMESPACE}" --create-namespace \
    --values /opt/harbor/values-base.yaml \
    --set "persistence.persistentVolumeClaim.registry.storageClass=${HARBOR_SC}" \
    --set "persistence.persistentVolumeClaim.jobservice.jobLog.storageClass=${HARBOR_SC}" \
    --set "persistence.persistentVolumeClaim.database.storageClass=${HARBOR_SC}" \
    --set "persistence.persistentVolumeClaim.redis.storageClass=${HARBOR_SC}" \
    --set "externalURL=${HARBOR_URL}" \
    --set "expose.nodePort.ports.http.nodePort=${HARBOR_NODEPORT}" \
    --set "harborAdminPassword=${HARBOR_ADMIN_PASSWORD}" \
    --wait --timeout 20m \
    || die "Harbor did not become ready. Inspect: kubectl -n ${HARBOR_NAMESPACE} get pods"

  info "waiting for the Harbor API on ${HARBOR_URL}"
  local deadline=$((SECONDS + 300))
  while (( SECONDS < deadline )); do
    if curl -fsS --max-time 5 -u "admin:${HARBOR_ADMIN_PASSWORD}" \
         "${HARBOR_URL}/api/v2.0/systeminfo" >/dev/null 2>&1; then
      ok "Harbor is serving at ${HARBOR_URL}"
      umask 077
      printf '%s\n' "${HARBOR_ADMIN_PASSWORD}" > "${OUTPUT_DIR}/harbor-admin-password"
      umask 022
      return 0
    fi
    sleep 5
  done
  die "Harbor's API never answered on ${HARBOR_URL}. Check: kubectl -n ${HARBOR_NAMESPACE} get pods"
}

push_demo_image() {
  local tar="${AIRGAP_DEMO_DIR}/${DEMO_IMAGE_NAME}.tar"
  [[ -f "${tar}" ]] || die "demo image tarball missing: ${tar}"

  info "pushing ${DEMO_IMAGE_NAME}:${DEMO_IMAGE_TAG} into Harbor as ${DEMO_IMAGE_REF}"
  run_logged skopeo copy --quiet \
    --dest-tls-verify=false \
    --dest-creds "admin:${HARBOR_ADMIN_PASSWORD}" \
    "docker-archive:${tar}" \
    "docker://${DEMO_IMAGE_REF}" \
    || die "failed to push the demo image into Harbor"

  # Prove it is really there before asking the cluster to pull it.
  curl -fsS -u "admin:${HARBOR_ADMIN_PASSWORD}" \
    "${HARBOR_URL}/api/v2.0/projects/${HARBOR_PROJECT}/repositories/${DEMO_IMAGE_NAME}/artifacts" \
    >/dev/null || die "Harbor does not list ${DEMO_IMAGE_REF} after the push"
  ok "image available in Harbor project '${HARBOR_PROJECT}'"
}

# --------------------------------------------------------------------------
# stage: demo workload
# --------------------------------------------------------------------------
deploy_demo() {
  local cfg="${STATE_DIR}/node-demo-config"
  rm -rf "${cfg}"; mkdir -p "${cfg}"

  [[ -s "${OUTPUT_DIR}/nodes.tsv" ]] || die "nodes.tsv was not produced by the post-install playbook"

  # One ConfigMap key per Kubernetes node name, holding that machine's facts.
  local idx name ip os kernel arch cpus memory
  while IFS=$'\t' read -r idx name ip os kernel arch cpus memory; do
    [[ -n "${name}" ]] || continue
    {
      echo "index=${idx}"
      echo "ip=${ip}"
      echo "os=${os}"
      echo "kernel=${kernel}"
      echo "arch=${arch}"
      echo "cpus=${cpus}"
      echo "memory=${memory}"
    } > "${cfg}/${name}"
    printf '%s\t%s\thttp://%s:%s/\n' "${idx}" "${name}" "${ip}" "${DEMO_NODEPORT}" >> "${cfg}/peers"
  done < "${OUTPUT_DIR}/nodes.tsv"

  printf '%s' "${CLUSTER_NAME}"    > "${cfg}/cluster-name"
  printf '%s' "${HARBOR_URL}"      > "${cfg}/registry"
  printf '%s' "${DEMO_IMAGE_REF}"  > "${cfg}/image"

  export DEMO_CONFIG_CHECKSUM
  DEMO_CONFIG_CHECKSUM="$(LC_ALL=C find "${cfg}" -type f | sort | xargs cat | sha256sum | cut -c1-16)"

  kubectl create namespace "${DEMO_NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f - >/dev/null

  kubectl -n "${DEMO_NAMESPACE}" create secret docker-registry harbor-pull \
    --docker-server="${HARBOR_HOST}:${HARBOR_NODEPORT}" \
    --docker-username=admin \
    --docker-password="${HARBOR_ADMIN_PASSWORD}" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null

  kubectl -n "${DEMO_NAMESPACE}" create configmap node-demo \
    --from-file="${cfg}" --dry-run=client -o yaml | kubectl apply -f - >/dev/null

  export DEMO_NAMESPACE DEMO_IMAGE_REF DEMO_NODEPORT
  envsubst '${DEMO_NAMESPACE} ${DEMO_IMAGE_REF} ${DEMO_NODEPORT} ${DEMO_CONFIG_CHECKSUM}' \
    < /opt/demo/manifests/node-demo.yaml > "${STATE_DIR}/node-demo.yaml"
  cp "${STATE_DIR}/node-demo.yaml" "${OUTPUT_DIR}/node-demo.yaml"

  run_logged kubectl apply -f "${STATE_DIR}/node-demo.yaml" \
    || die "could not apply the demo manifests"

  if [[ -n "${VIP_ADDRESS}" ]]; then
    export INGRESS_CLASS VIP_ADDRESS
    envsubst '${DEMO_NAMESPACE} ${INGRESS_CLASS} ${VIP_ADDRESS}' \
      < /opt/demo/manifests/node-demo-ingress.yaml > "${STATE_DIR}/node-demo-ingress.yaml"
    cp "${STATE_DIR}/node-demo-ingress.yaml" "${OUTPUT_DIR}/node-demo-ingress.yaml"
    run_logged kubectl apply -f "${STATE_DIR}/node-demo-ingress.yaml" \
      || die "could not apply the demo Ingress"
    ok "demo also published through Traefik on http://${VIP_ADDRESS}/"
  fi

  info "waiting for one pod per node to pull ${DEMO_IMAGE_REF} from Harbor"
  run_logged kubectl -n "${DEMO_NAMESPACE}" rollout status daemonset/node-demo --timeout=6m \
    || die "the demo DaemonSet never became ready. Check: kubectl -n ${DEMO_NAMESPACE} describe pods"
  ok "demo workload running on every node"
}

# --------------------------------------------------------------------------
# stage: verify
# --------------------------------------------------------------------------
verify_demo() {
  local failed=0 idx name ip body served
  while IFS=$'\t' read -r idx name ip _rest; do
    [[ -n "${ip}" ]] || continue
    if ! body="$(curl -fsS --max-time 10 "http://${ip}:${DEMO_NODEPORT}/info.json" 2>&1)"; then
      warn "node ${idx} (${ip}) did not answer on port ${DEMO_NODEPORT}"
      failed=1
      continue
    fi
    served="$(jq -r '.nodeName' <<< "${body}" 2>/dev/null || echo '?')"
    if [[ "${served}" == "${name}" ]]; then
      ok "http://${ip}:${DEMO_NODEPORT}/  ->  Node ${idx} (${served})"
    else
      warn "http://${ip}:${DEMO_NODEPORT}/ was answered by '${served}', expected '${name}'"
      failed=1
    fi
  done < "${OUTPUT_DIR}/nodes.tsv"
  (( failed == 0 )) || warn "some nodes did not serve their own page; see the log at ${LOG_FILE}"

  # The ingress is the other half of the story: same DaemonSet, but reached
  # through the VIP and balanced, so repeated calls should not always land on
  # the same node.
  if [[ -n "${VIP_ADDRESS}" ]]; then
    local seen=() answer
    for _ in 1 2 3 4 5 6; do
      answer="$(curl -fsS --max-time 10 "http://${VIP_ADDRESS}/info.json" 2>/dev/null \
                | jq -r '.nodeName' 2>/dev/null || true)"
      [[ -n "${answer}" ]] && seen+=("${answer}")
    done
    if (( ${#seen[@]} == 0 )); then
      warn "http://${VIP_ADDRESS}/ did not answer - check the Traefik ingress and the VIP"
    else
      local distinct
      distinct="$(printf '%s\n' "${seen[@]}" | sort -u | tr '\n' ' ' | sed 's/ $//')"
      ok "http://${VIP_ADDRESS}/  ->  answered by: ${distinct}"
    fi
  fi
}

# --------------------------------------------------------------------------
# stage: summary
# --------------------------------------------------------------------------
write_summary() {
  local summary="${OUTPUT_DIR}/SUMMARY.md" nodes_md=""
  local idx name ip os _rest
  while IFS=$'\t' read -r idx name ip os _rest; do
    [[ -n "${ip}" ]] || continue
    nodes_md+="| ${idx} | \`${name}\` | ${ip} | ${os} | <http://${ip}:${DEMO_NODEPORT}/> |"$'\n'
  done < "${OUTPUT_DIR}/nodes.tsv"

  local VIP_SUMMARY
  if [[ -n "${VIP_ADDRESS}" ]]; then
    VIP_SUMMARY="\`${VIP_ADDRESS}\` floats between the servers (kube-vip, ARP mode) and serves
the API on :6443, Traefik on :80/:443 and Harbor on :${HARBOR_NODEPORT}. Losing the node
that currently holds it moves the address rather than the service.

The nodes still join through \`${NODE_IPS[0]}\` when k3s is installed, so keep that
address reachable if you re-run the installer."
  else
    VIP_SUMMARY="Not configured, so services are reached per node and \`${NODE_IPS[0]}\` is a
single point of failure for new image pulls. Re-run with \`--vip <address>\` to put
one stable address in front of the API, the ingress and the registry."
  fi

  cat > "${summary}" <<MD
# ${CLUSTER_NAME}

Installed $(date -u '+%Y-%m-%d %H:%M UTC') by the airgapped installer.

## Nodes

| # | Node | IP | OS | Demo page |
|---|------|----|----|-----------|
${nodes_md}
## Virtual IP

${VIP_SUMMARY}

## Harbor

- URL: <${HARBOR_URL}>
- User: \`admin\`
- Password: see \`harbor-admin-password\` next to this file
- Demo image: \`${DEMO_IMAGE_REF}\`

Push your own images from a machine that can reach the registry:

\`\`\`sh
docker login ${HARBOR_HOST}:${HARBOR_NODEPORT}      # admin / <password>
docker tag myapp:1.0 ${HARBOR_HOST}:${HARBOR_NODEPORT}/${HARBOR_PROJECT}/myapp:1.0
docker push ${HARBOR_HOST}:${HARBOR_NODEPORT}/${HARBOR_PROJECT}/myapp:1.0
\`\`\`

Harbor is served over plain HTTP, so add it to the pushing client's insecure
registry list (\`/etc/docker/daemon.json\`: \`{"insecure-registries":["${HARBOR_HOST}:${HARBOR_NODEPORT}"]}\`).
Every k3s node is already configured for it via \`/etc/rancher/k3s/registries.yaml\`.

## Cluster access

\`\`\`sh
export KUBECONFIG=\$PWD/kubeconfig
kubectl get nodes -o wide
kubectl -n ${DEMO_NAMESPACE} get pods -o wide
\`\`\`

The kubeconfig points at \`${CLUSTER_ENDPOINT}\`.

k3s runs with embedded etcd across all ${#NODE_IPS[@]} servers and
\`secrets-encryption\` enabled.

## Storage

Longhorn is the default StorageClass, replicating every volume across the nodes'
data disks. k3s's \`local-path\` is still installed but no longer the default, so
a PVC that names no class gets replicated storage.

Harbor's volumes are on \`${HARBOR_SC}\`. A PVC's class cannot be changed once it
has bound, so moving an existing Harbor to a different class means deleting its
volumes first.

\`\`\`sh
kubectl get storageclass
kubectl -n ${LONGHORN_NAMESPACE} get nodes.longhorn.io
\`\`\`
MD

  {
    echo "CLUSTER_NAME=${CLUSTER_NAME}"
    echo "NODE_IPS=${NODE_IPS[*]}"
    echo "HARBOR_URL=${HARBOR_URL}"
    echo "DEMO_IMAGE_REF=${DEMO_IMAGE_REF}"
    echo "DEMO_URL_TEMPLATE=http://<node-ip>:${DEMO_NODEPORT}/"
    echo "VIP_ADDRESS=${VIP_ADDRESS}"
    echo "CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}"
    echo "HARBOR_STORAGE_CLASS=${HARBOR_SC}"
  } > "${OUTPUT_DIR}/cluster.env"

  printf '\n'
  rule
  printf '      %sCluster is up.%s\n\n' "${C_GREEN}${C_BOLD}" "${C_RESET}"
  if [[ -n "${VIP_ADDRESS}" ]]; then
    info "VIP       ${VIP_ADDRESS}  (api :6443, ingress :80, harbor :${HARBOR_NODEPORT})"
  fi
  info "Harbor    ${HARBOR_URL}  (admin / $(cat "${OUTPUT_DIR}/harbor-admin-password"))"
  info "Storage   longhorn (default) · harbor on ${HARBOR_SC}"
  info "Demo      http://<node-ip>:${DEMO_NODEPORT}/"
  info "kubeconfig, summary and logs are in the output directory on the host"
  rule
}

# --------------------------------------------------------------------------
# stage: reset
# --------------------------------------------------------------------------
run_reset() {
  warn "this uninstalls k3s and destroys all cluster data on: ${NODE_IPS[*]}"
  if [[ -z "${ASSUME_YES:-}" ]]; then
    confirm "Really uninstall k3s from these machines?" || die "aborted - nothing was changed"
  fi
  run_logged ansible-playbook /opt/k3s-ansible/playbooks/reset.yml \
    -e "@${STATE_DIR}/vars.yml" \
    || die "reset failed"
  ok "k3s removed from all nodes"
}
